import 'spending_category.dart';

const Map<String, SpendingCategory> merchantMappings = {
  // Grocery / Supermarket
  'costco': SpendingCategory.costco,
  'whole foods': SpendingCategory.wholeFoods,
  'wholefoods': SpendingCategory.wholeFoods,
  'trader joe': SpendingCategory.groceries,
  "trader joe's": SpendingCategory.groceries,
  'kroger': SpendingCategory.groceries,
  'safeway': SpendingCategory.groceries,
  'publix': SpendingCategory.groceries,
  'aldi': SpendingCategory.groceries,
  'h-e-b': SpendingCategory.groceries,
  'wegmans': SpendingCategory.groceries,
  'sprouts': SpendingCategory.groceries,
  // General Retail
  'amazon': SpendingCategory.amazon,
  'target': SpendingCategory.target,
  'walmart': SpendingCategory.walmart,
  'best buy': SpendingCategory.online,
  'apple store': SpendingCategory.online,
  'ikea': SpendingCategory.general,
  // Coffee
  'starbucks': SpendingCategory.coffee,
  'dunkin': SpendingCategory.coffee,
  "peet's": SpendingCategory.coffee,
  'philz': SpendingCategory.coffee,
  // Fast Food / Dining
  'mcdonalds': SpendingCategory.fastFood,
  "mcdonald's": SpendingCategory.fastFood,
  'chipotle': SpendingCategory.fastFood,
  'chick-fil-a': SpendingCategory.fastFood,
  'subway': SpendingCategory.fastFood,
  'taco bell': SpendingCategory.fastFood,
  "wendy's": SpendingCategory.fastFood,
  'popeyes': SpendingCategory.fastFood,
  'panda express': SpendingCategory.fastFood,
  'doordash': SpendingCategory.dining,
  'uber eats': SpendingCategory.dining,
  'grubhub': SpendingCategory.dining,
  // Transit / Ride Share
  'uber': SpendingCategory.transit,
  'lyft': SpendingCategory.transit,
  // Streaming
  'netflix': SpendingCategory.streaming,
  'spotify': SpendingCategory.streaming,
  'hulu': SpendingCategory.streaming,
  'disney+': SpendingCategory.streaming,
  'disney plus': SpendingCategory.streaming,
  'apple tv': SpendingCategory.streaming,
  'hbo max': SpendingCategory.streaming,
  'youtube': SpendingCategory.streaming,
  'peacock': SpendingCategory.streaming,
  'paramount+': SpendingCategory.streaming,
  // Drugstores
  'cvs': SpendingCategory.drugstores,
  'walgreens': SpendingCategory.drugstores,
  'rite aid': SpendingCategory.drugstores,
  // Gas Stations
  'shell': SpendingCategory.gas,
  'exxon': SpendingCategory.gas,
  'chevron': SpendingCategory.gas,
  'bp': SpendingCategory.gas,
  'mobil': SpendingCategory.gas,
  'costco gas': SpendingCategory.gas,
  'arco': SpendingCategory.gas,
  '76': SpendingCategory.gas,
  'speedway': SpendingCategory.gas,
  // Travel / Airlines / Hotels
  'united': SpendingCategory.airfare,
  'delta': SpendingCategory.airfare,
  'american airlines': SpendingCategory.airfare,
  'southwest': SpendingCategory.airfare,
  'jetblue': SpendingCategory.airfare,
  'spirit': SpendingCategory.airfare,
  'frontier': SpendingCategory.airfare,
  'marriott': SpendingCategory.hotels,
  'hilton': SpendingCategory.hotels,
  'hyatt': SpendingCategory.hotels,
  'airbnb': SpendingCategory.hotels,
  'expedia': SpendingCategory.travel,
  'booking.com': SpendingCategory.hotels,
  // PayPal / Fintech
  'paypal': SpendingCategory.paypal,
  'venmo': SpendingCategory.paypal,
  // Entertainment
  'amc': SpendingCategory.entertainment,
  'regal': SpendingCategory.entertainment,
  'ticketmaster': SpendingCategory.entertainment,
  'stubhub': SpendingCategory.entertainment,
  // Rent
  'rent': SpendingCategory.rent,
  'landlord': SpendingCategory.rent,
  'apartment': SpendingCategory.rent,
};
